### ISSUE TITLE
binip_in_cidrs compare with nil error

### ISSUE THREAD

**Issue by gideonw** [hamishforbes/lua-resty-iputils#11]
This may be a kong issue and not an error with this lib, but I ran into this error while using kong.

I configured my whitelist cidr as 0.0.0.0/0 and when a request comes in from any IP I get the following error.

```
*9520688 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/resty/iputils.lua:199: attempt to compare number with nil
 stack traceback:
 coroutine 0:
    /usr/local/share/lua/5.1/resty/iputils.lua: in function 'binip_in_cidrs'
    ...al/share/lua/5.1/kong/plugins/ip-restriction/handler.lua:78: in function 'access'
    /usr/local/share/lua/5.1/kong.lua:350: in function 'access'
    access_by_lua(nginx-kong.conf:89):2: in function <access_by_lua(nginx-kong.conf:89):1>
    
, client: <remote_ip>, server: kong, request: "GET /api/health HTTP/1.1", host: "<host>"
```

**Comment by hamishforbes** [comment]
Hi, Can you check which version you're using? 
This is either a bug with the solution to #9 or an older version

**Comment by gideonw** [comment]
Hmm, it appears that Kong is behind.
https://github.com/Mashape/kong/blob/master/kong-0.11.0-0.rockspec#L26

**Comment by gideonw** [comment]
I updated that file on my kong deployment and it has fixed the error.
