### ISSUE TITLE
ip_in_cidrs : attempt to compare nil with number

### ISSUE THREAD

**Issue by HamzaKhait** [hamishforbes/lua-resty-iputils#17]
Hello,

I created a Prosody lua module and I want to verify client's IP but I've got an error the following error : 
```
Apr 29 17:38:21 mod_bosh	error	Traceback[bosh]: /usr/local/share/lua/5.1/resty/iputils.lua:189: attempt to compare nil with number stack traceback:
	/usr/local/share/lua/5.1/resty/iputils.lua:189: in function 'ip_in_cidrs'

```
Here's the code
```
		local testArray={
			"172.20.41.65/32",
			"127.0.0.1"
		}
		log("info", "ip_in_cidrs result : "..tostring(iputils.ip_in_cidrs("172.20.41.65",testArray)));

```
is there any way to avoid this error please ? 

Thanks

**Comment by hamishforbes** [comment]
As stated in the docs, you need to convert the CIDRs to numeric representations using the `parse_cidrs` function, you can't use strings.

**Comment by HamzaKhait** [comment]
Oh that was tricky. I didn't see the line
`whitelist = iputils.parse_cidrs(whitelist_ips)`

Thank you @hamishforbes
