### ISSUE TITLE
Attempt to read a non-existent global 'ngx'

### ISSUE THREAD

**Issue by HamzaKhait** [hamishforbes/lua-resty-iputils#18]
Hello,

I am using lua-resty-iputils for a custom module of Prosody but I get the error below when starting the app : 
```
Jan 07 14:46:17 startup warn    Attempt to read a non-existent global 'ngx'
stack traceback:
        /usr/local/share/lua/5.2/resty/iputils.lua:34: in main chunk
        [C]: in function '_real_require'
        /usr/lib/prosody/util/startup.lua:144: in function 'require'
        /opt/prosody-webconf-modules/mod_jitsi_stats.lua:15: in main chunk
        [C]: in function 'xpcall'
        /usr/lib/prosody/core/modulemanager.lua:178: in function 'do_load_module'
        /usr/lib/prosody/core/modulemanager.lua:256: in function 'load'
        /usr/lib/prosody/core/modulemanager.lua:78: in function '?'
        /usr/lib/prosody/util/events.lua:79: in function </usr/lib/prosody/util/events.lua:75>
        (...tail calls...)
        /usr/lib/prosody/core/hostmanager.lua:108: in function 'activate'
        /usr/lib/prosody/core/hostmanager.lua:58: in function '?'
        /usr/lib/prosody/util/events.lua:79: in function </usr/lib/prosody/util/events.lua:75>
        (...tail calls...)
        /usr/lib/prosody/util/startup.lua:330: in function 'prepare_to_start'
        /usr/lib/prosody/util/startup.lua:551: in function 'f'
        /usr/lib/prosody/util/async.lua:139: in function 'func'
        /usr/lib/prosody/util/async.lua:127: in function </usr/lib/prosody/util/async.lua:125>
```
 the problem seems to be caused by this line https://github.com/hamishforbes/lua-resty-iputils/blob/master/lib/resty/iputils.lua#L33.

Any ideas how to solve this please ? 
BTW, I am using LUA version 5.2.

Thanks

**Comment by hamishforbes** [comment]
Not sure what Prosody is, but this library is *intended* for use with Openresty not vanilla Lua.

There is the most basic attempt to allow it to run in vanilla Lua for testing purposes, but that requires checking if the `ngx` global is available.   
If we're not even allowed to do that then there's very little chance of this working in whatever environment you're using

**Comment by HamzaKhait** [comment]
Prosody is an XMPP server used by Jitsi video-conferencing app.
Actually, lua-resty-iputils used to work with LUA 5.1 without any particular issue.
I got the error above after upgrading to LUA 5.2
