### ISSUE TITLE
Installation as nginx module

### ISSUE THREAD

**Issue by abarre** [hamishforbes/lua-resty-iputils#8]
I don't understand how I can install this module in nginx that has the `lua-nginx-module` from openresty .

I cloned the git repo and added in the configure line like so : `--add-module=/tmp/lua-resty-iputils/`.

However, I have the following line : 
```
adding module in /tmp/lua-resty-iputils
./configure: error: no /tmp/lua-resty-iputils/config was found
```

Could you let me know how do you install this module ?

**Comment by hamishforbes** [comment]
Hi, This is a Lua module not an nginx module.

You simply need to set your [lua_package_path](https://github.com/openresty/lua-nginx-module#lua_package_path) to include the path to this lib and you should be able to `require()` it.

You could also try using luarocks to install it.

If you really want to build it into your openresty release you can use this method I think: https://github.com/openresty/lua-nginx-module#statically-linking-pure-lua-modules
